### ISSUE TITLE
Some questions about drawing

### ISSUE THREAD

**Issue by xuegao19891015** [jdemeul/HomDels#1]
Hello, teacher
Some questions about drawing ，
I'm very interested Tumour ploidy and purity across cancer types Fig. 1， R code Could you provide it ? 
Best to provide an example，I will study hard.
Thks

**Comment by jdemeul** [comment]
I don't immediately have the code handy, but you can easily do this using the `ggplot2` and/or `ggforce` packages for R. See `geom_violin` and `geom_sina`, respectively.
